apiVersion: v1
kind: PersistentVolume
metadata: 
  name: host-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # 이 볼륨이 단일 노드에 의해 읽기/쓰기 볼륨으로 마운트될 수 있다. 이 테스트는 단일 노드를 사용하므로 이걸 쓴다.
    # - ReadOnlyMany # 읽기 전용이면서 여러 노드에서 요청할 수 있다.
    # - ReadWriteMany # 읽기와 쓰기를 여러 노드에서 요청할 수 있다.
  hostPath: 
    path: /data
    type: DirectoryOrCreate 