apiVersion: v1
kind: Pod
metadata:
  name: event-simulator-pod
spec:
  containers:
    - name: event-simulator
      image: kodekloud/event-simulator
    - name: image-processor
      image: some-image-processor

# 도커 컨테이너를 파드로 띄워 log를 확인할 수 있는 간단한 모니터링 방법
# even-simulator라는 컨테이너의 로그 확인
# kubectl logs -f event-simulator-pod even-simulator