apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: wonyongg/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              value: localhost # 동일한 pod에서 실행되는 2개의 컨테이너가 서로 통신하는 경우에 localhost라는 특수한 주소를 사용하면 통신할 수 있다.
        - name: auth
          image: wonyongg/kub-demo-auth:latest
          

