apiVersion: v1
kind: ReplicationController
metadata: # Replicaion Controller 용
  name: myapp-rc
  labels:
    app: myapp
    type: front-end

spec: # Replicaion Controller 용
  template:
    metadata: # POD 용
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec: # POD 용
      containers:
      - name: nginx-container
        image: nginx

  replicas: 3 # 복제 컨트롤러 수

  # kubectl create -f 2-replication-controller.yml      
  # 복제된 파드 3 개 확인