apiVersion: v1
kind: Service
metadata:
  name: myapp-service

spec:
  type: NodePort # Range: 30000-32767
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008 # 지정하지 않을 경우, 위의 Range에서 자동 할당됨
  selector:
    app: myapp
    type: front-end

# kubectl create -f 4-service.yml
# kubectl get services