apiVersion: v1
kind: Service
metadata:
  name: back-end

spec:
  type: ClusterIP # default
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: myapp
    type: back-end

# kubectl create -f 4-service-clusterip.yml
# kubectl get services