apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_Host: bXlzcWw= # mysql을 byte64로 인코딩한 값
  DB_User: cm9vdA== # root를 byte64로 인코딩한 값
  DB_Password: MTIzNA== # 1234를 byte64로 인코딩한 값

#  echo -n 'mysql' | base64 ->  mysql이란 문자열을 base64로 인코딩하는 명령어
# kubectl get secrets
# kubectl describe secrets(비밀 정보가 바이트 수로 나옴)
# kubectl get secret app-secret -o yaml(비밀 정보가 base64로 인코딩된 문자열 값이 나옴)

---

apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
  containers:
    - name: simple-webapp-color
      image: simple-webapp-color
      ports:
        - containerPort: 8080
# env
      envFrom:
        - secretRef:
            name: app-secret
# single env
      env:
        - name: DB_Password
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_Password
# volume
      volumes:
        - name: app-secret-volume
          secret:
            secretName: app-secret
      

